export const courses = {
    courses: [
        {
            "id": 14,
            "name": "Belajar Fundamental Aplikasi Android",
            "technology": "Android,Multi Platform",
            "hours_to_study": 140,
            "rating": "4.84",
            "level": "PROFESSIONAL",
            "learning_path": "Android Developer",
            "total_modules": 107,
            "registered_students": 41782
        },
        {
            "id": 51,
            "name": "Belajar Membuat Aplikasi Android untuk Pemula",
            "technology": "Android,Multi Platform",
            "hours_to_study": 60,
            "rating": "4.87",
            "level": "BEGINNER",
            "learning_path": "Android Developer",
            "total_modules": 49,
            "registered_students": 116208
        },
        {
            "id": 60,
            "name": "Memulai Pemrograman Dengan Java",
            "technology": "Android,Multi Platform",
            "hours_to_study": 15,
            "rating": "4.86",
            "level": "FUNDAMENTAL",
            "learning_path": "Android Developer",
            "total_modules": 42,
            "registered_students": 79824
        },
        {
            "id": 80,
            "name": "Memulai Pemrograman dengan Kotlin",
            "technology": "Android,Multi Platform",
            "hours_to_study": 50,
            "rating": "4.84",
            "level": "FUNDAMENTAL",
            "learning_path": "Android Developer",
            "total_modules": 132,
            "registered_students": 59240
        },
        {
            "id": 86,
            "name": "Memulai Pemrograman dengan Python",
            "technology": "Data,Machine Learning",
            "hours_to_study": 35,
            "rating": "4.8",
            "level": "FUNDAMENTAL",
            "learning_path": "Machine Learning Developer",
            "total_modules": 91,
            "registered_students": 111203
        },
        {
            "id": 120,
            "name": "Memulai Pemrograman Dengan C",
            "technology": "Multi Platform",
            "hours_to_study": 15,
            "rating": "4.85",
            "level": "FUNDAMENTAL",
            "learning_path": "Basic Programming",
            "total_modules": 48,
            "registered_students": 49681
        },
        {
            "id": 123,
            "name": "Belajar Dasar Pemrograman Web",
            "technology": "Web",
            "hours_to_study": 45,
            "rating": "4.87",
            "level": "FUNDAMENTAL",
            "learning_path": "Front-End Web Developer",
            "total_modules": 131,
            "registered_students": 176868
        },
        {
            "id": 133,
            "name": "Menjadi Google Cloud Engineer",
            "technology": "Cloud,Web",
            "hours_to_study": 42,
            "rating": "4.87",
            "level": "PROFESSIONAL",
            "learning_path": "Azure Cloud Developer",
            "total_modules": 85,
            "registered_students": 8709
        },
        {
            "id": 145,
            "name": "Memulai Pemrograman Dengan Swift",
            "technology": "IOS",
            "hours_to_study": 40,
            "rating": "4.85",
            "level": "FUNDAMENTAL",
            "learning_path": "iOS Developer",
            "total_modules": 95,
            "registered_students": 8070
        },
        {
            "id": 159,
            "name": "Belajar Membuat Aplikasi Flutter untuk Pemula",
            "technology": "Android,IOS,Multi Platform",
            "hours_to_study": 40,
            "rating": "4.87",
            "level": "BEGINNER",
            "learning_path": "Multi-Platform App Developer",
            "total_modules": 51,
            "registered_students": 21135
        },
        {
            "id": 163,
            "name": "Belajar Fundamental Front-End Web Development",
            "technology": "Web",
            "hours_to_study": 80,
            "rating": "4.88",
            "level": "BEGINNER",
            "learning_path": "Front-End Web Developer",
            "total_modules": 114,
            "registered_students": 28216
        },
        {
            "id": 165,
            "name": "Menjadi Android Developer Expert",
            "technology": "Android",
            "hours_to_study": 90,
            "rating": "4.8",
            "level": "PROFICIENT",
            "learning_path": "Android Developer",
            "total_modules": 87,
            "registered_students": 5507
        },
        {
            "id": 169,
            "name": "Belajar Prinsip Pemrograman SOLID",
            "technology": "Android,IOS,Multi Platform,Web",
            "hours_to_study": 15,
            "rating": "4.87",
            "level": "PROFESSIONAL",
            "learning_path": "Android Developer",
            "total_modules": 41,
            "registered_students": 40615
        },
        {
            "id": 171,
            "name": "Belajar Membuat Aplikasi iOS untuk Pemula",
            "technology": "IOS",
            "hours_to_study": 40,
            "rating": "4.84",
            "level": "BEGINNER",
            "learning_path": "iOS Developer",
            "total_modules": 74,
            "registered_students": "3471\\"
        },
        {
            "id": 177,
            "name": "Belajar Dasar Visualisasi Data",
            "technology": "Data,Machine Learning",
            "hours_to_study": 16,
            "rating": "4.85",
            "level": "FUNDAMENTAL",
            "learning_path": "Machine Learning Developer",
            "total_modules": 50,
            "registered_students": 88419
        },
        {
            "id": 184,
            "name": "Belajar Machine Learning untuk Pemula",
            "technology": "Machine Learning",
            "hours_to_study": 30,
            "rating": "4.83",
            "level": "BEGINNER",
            "learning_path": "Machine Learning Developer",
            "total_modules": 56,
            "registered_students": 89511
        },
        {
            "id": 185,
            "name": "Belajar Pengembangan Machine Learning",
            "technology": "Machine Learning",
            "hours_to_study": 40,
            "rating": "4.83",
            "level": "PROFESSIONAL",
            "learning_path": "Machine Learning Developer",
            "total_modules": 70,
            "registered_students": 8051
        },
        {
            "id": 191,
            "name": "Memulai Pemrograman dengan Dart",
            "technology": "Multi Platform",
            "hours_to_study": 20,
            "rating": "4.84",
            "level": "FUNDAMENTAL",
            "learning_path": "Multi-Platform App Developer",
            "total_modules": 81,
            "registered_students": 23658
        },
        {
            "id": 195,
            "name": "Belajar Fundamental Aplikasi Flutter",
            "technology": "Android,IOS,Multi Platform",
            "hours_to_study": 70,
            "rating": "4.83",
            "level": "PROFESSIONAL",
            "learning_path": "Multi-Platform App Developer",
            "total_modules": 87,
            "registered_students": 4475
        },
        {
            "id": 199,
            "name": "Menjadi Flutter Developer Expert",
            "technology": "Android,IOS,Multi Platform",
            "hours_to_study": 85,
            "rating": "4.85",
            "level": "INTERMEDIATE",
            "learning_path": "Multi-Platform App Developer",
            "total_modules": 93,
            "registered_students": 2233
        },
        {
            "id": 202,
            "name": "Belajar Fundamental Aplikasi iOS",
            "technology": "IOS",
            "hours_to_study": 70,
            "rating": "4.83",
            "level": "PROFESSIONAL",
            "learning_path": "iOS Developer",
            "total_modules": 127,
            "registered_students": 1343
        },
        {
            "id": 209,
            "name": "Menjadi iOS Developer Expert",
            "technology": "IOS",
            "hours_to_study": 70,
            "rating": "4.85",
            "level": "INTERMEDIATE",
            "learning_path": "iOS Developer",
            "total_modules": 126,
            "registered_students": 952
        },
        {
            "id": 219,
            "name": "Menjadi Front-End Web Developer Expert",
            "technology": "Web",
            "hours_to_study": 110,
            "rating": "4.88",
            "level": "INTERMEDIATE",
            "learning_path": "Front-End Web Developer",
            "total_modules": 213,
            "registered_students": 8508
        },
        {
            "id": 251,
            "name": "Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)",
            "technology": "Cloud",
            "hours_to_study": 15,
            "rating": "4.81",
            "level": "FUNDAMENTAL",
            "learning_path": "Back-End Developer",
            "total_modules": 87,
            "registered_students": 177521
        },
        {
            "id": 256,
            "name": "Belajar Dasar Pemrograman JavaScript",
            "technology": "Web",
            "hours_to_study": 45,
            "rating": "4.86",
            "level": "FUNDAMENTAL",
            "learning_path": "Front-End Web Developer",
            "total_modules": 116,
            "registered_students": 152164
        },
        {
            "id": 261,
            "name": "Belajar Membuat Aplikasi Back-End untuk Pemula",
            "technology": "Cloud,Web",
            "hours_to_study": 45,
            "rating": "4.89",
            "level": "BEGINNER",
            "learning_path": "Back-End Developer",
            "total_modules": 114,
            "registered_students": 103744
        },
        {
            "id": 266,
            "name": "Architecting on AWS (Membangun Arsitektur Cloud di AWS)",
            "technology": "Cloud",
            "hours_to_study": 40,
            "rating": "4.83",
            "level": "PROFESSIONAL",
            "learning_path": "Back-End Developer",
            "total_modules": 170,
            "registered_students": 13564
        },
        {
            "id": 271,
            "name": "Belajar Fundamental Aplikasi Back-End",
            "technology": "Cloud,Web",
            "hours_to_study": 90,
            "rating": "4.89",
            "level": "PROFESSIONAL",
            "learning_path": "Back-End Developer",
            "total_modules": 189,
            "registered_students": 6071
        },
        {
            "id": 276,
            "name": "Menjadi Back-End Developer Expert",
            "technology": "Cloud,Web",
            "hours_to_study": 82,
            "rating": "4.89",
            "level": "INTERMEDIATE",
            "learning_path": "Back-End Developer",
            "total_modules": 116,
            "registered_students": 3216
        },
        {
            "id": 292,
            "name": "Meniti Karier sebagai Software Developer",
            "technology": "Android,Cloud,IOS,Machine Learning,Multi Platform,Web",
            "hours_to_study": 7,
            "rating": "4.9",
            "level": "FUNDAMENTAL",
            "learning_path": "Basic Programming",
            "total_modules": 53,
            "registered_students": 19628
        },
        {
            "id": 302,
            "name": "Pengenalan ke Logika Pemrograman (Programming Logic 101)",
            "technology": "Data",
            "hours_to_study": 6,
            "rating": "4.91",
            "level": "FUNDAMENTAL",
            "learning_path": "Basic Programming",
            "total_modules": 37,
            "registered_students": 34568
        },
        {
            "id": 313,
            "name": "Belajar Membuat Augmented Reality dengan Lens Studio",
            "technology": "AR/VR/MR",
            "hours_to_study": 20,
            "rating": "4.88",
            "level": "BEGINNER",
            "learning_path": "Augmented Reality dengan Lens Studio",
            "total_modules": 56,
            "registered_students": 14898
        },
        {
            "id": 315,
            "name": "Belajar Membuat Front-End Web untuk Pemula",
            "technology": "Web",
            "hours_to_study": 45,
            "rating": "4.87",
            "level": "BEGINNER",
            "learning_path": "Front-End Web Developer",
            "total_modules": 69,
            "registered_students": 98355
        },
        {
            "id": 319,
            "name": "Machine Learning Terapan",
            "technology": "Machine Learning",
            "hours_to_study": 40,
            "rating": "4.87",
            "level": "INTERMEDIATE",
            "learning_path": "Machine Learning Developer",
            "total_modules": 109,
            "registered_students": 4034
        },
        {
            "id": 332,
            "name": "Menjadi Google Cloud Architect",
            "technology": "Cloud",
            "hours_to_study": 35,
            "rating": "4.87",
            "level": "PROFESSIONAL",
            "learning_path": "Google Cloud Professional",
            "total_modules": 79,
            "registered_students": 2798
        },
        {
            "id": 337,
            "name": "Belajar Dasar Google Cloud",
            "technology": "Cloud",
            "hours_to_study": 12,
            "rating": "4.88",
            "level": "FUNDAMENTAL",
            "learning_path": "Google Cloud Professional",
            "total_modules": 78,
            "registered_students": 8445
        },
        {
            "id": 342,
            "name": "Belajar Membuat Aplikasi Back-End untuk Pemula dengan Google Cloud",
            "technology": "Cloud,Web",
            "hours_to_study": 45,
            "rating": "4.87",
            "level": "BEGINNER",
            "learning_path": "Google Cloud Professional",
            "total_modules": 108,
            "registered_students": 7482
        },
        {
            "id": 352,
            "name": "Belajar Pengembangan Aplikasi Android Intermediate",
            "technology": "Android",
            "hours_to_study": 150,
            "rating": "4.8",
            "level": "INTERMEDIATE",
            "learning_path": "Android Developer",
            "total_modules": 115,
            "registered_students": 6928
        },
        {
            "id": 382,
            "name": "Belajar Dasar-Dasar DevOps",
            "technology": "Cloud,Web",
            "hours_to_study": 15,
            "rating": "4.87",
            "level": "FUNDAMENTAL",
            "learning_path": "DevOps Engineer",
            "total_modules": 38,
            "registered_students": 45052
        },
        {
            "id": 387,
            "name": "Belajar Jaringan Komputer untuk Pemula",
            "technology": "Cloud,Web",
            "hours_to_study": 25,
            "rating": "4.9",
            "level": "BEGINNER",
            "learning_path": "DevOps Engineer",
            "total_modules": 62,
            "registered_students": 43516
        },
        {
            "id": 403,
            "name": "Belajar Membuat Aplikasi Web dengan React",
            "technology": "Web",
            "hours_to_study": 35,
            "rating": "4.9",
            "level": "BEGINNER",
            "learning_path": "React Developer",
            "total_modules": 56,
            "registered_students": 17330
        },
        {
            "id": 413,
            "name": "Belajar Fundamental Aplikasi Web dengan React",
            "technology": "Web",
            "hours_to_study": 55,
            "rating": "4.92",
            "level": "PROFESSIONAL",
            "learning_path": "React Developer",
            "total_modules": 66,
            "registered_students": 2798
        },
        {
            "id": 418,
            "name": "Menjadi React Web Developer Expert",
            "technology": "Web",
            "hours_to_study": 70,
            "rating": "4.9",
            "level": "INTERMEDIATE",
            "learning_path": "React Developer",
            "total_modules": 103,
            "registered_students": 1837
        },
        {
            "id": 423,
            "name": "Menjadi Linux System Administrator",
            "technology": "Linux",
            "hours_to_study": 25,
            "rating": "4.91",
            "level": "PROFESSIONAL",
            "learning_path": "DevOps Engineer",
            "total_modules": 64,
            "registered_students": 2940
        },
        {
            "id": 428,
            "name": "Belajar Implementasi CI/CD",
            "technology": "Cloud,Web",
            "hours_to_study": 30,
            "rating": "4.87",
            "level": "PROFESSIONAL",
            "learning_path": "DevOps Engineer",
            "total_modules": 64,
            "registered_students": 2546
        },
        {
            "id": 433,
            "name": "Belajar Membangun Arsitektur Microservices",
            "technology": "Cloud,Web",
            "hours_to_study": 60,
            "rating": "4.86",
            "level": "INTERMEDIATE",
            "learning_path": "DevOps Engineer",
            "total_modules": 94,
            "registered_students": 1408
        },
        {
            "id": 443,
            "name": "Machine Learning Operations (MLOps)",
            "technology": "Machine Learning",
            "hours_to_study": 45,
            "rating": "4.49",
            "level": "INTERMEDIATE",
            "learning_path": "Machine Learning Developer",
            "total_modules": 72,
            "registered_students": 2245
        },
        {
            "id": 480,
            "name": "Belajar Pengembangan Aplikasi Flutter Intermediate",
            "technology": "Android,IOS,Multi Platform",
            "hours_to_study": 80,
            "rating": "4.85",
            "level": "INTERMEDIATE",
            "learning_path": "Multi-Platform App Developer",
            "total_modules": 93,
            "registered_students": 1037
        },
        {
            "id": 555,
            "name": "Belajar Analisis Data dengan Python",
            "technology": "Data",
            "hours_to_study": 30,
            "rating": "4.8",
            "level": "BEGINNER",
            "learning_path": "Data Scientist",
            "total_modules": 61,
            "registered_students": 27347
        },
        {
            "id": 565,
            "name": "Belajar Tools Front-End Web Intermediate",
            "technology": "Web",
            "hours_to_study": 65,
            "rating": "4.82",
            "level": "INTERMEDIATE",
            "learning_path": "Front-End Web Developer",
            "total_modules": 131,
            "registered_students": 1538
        },
        {
            "id": 590,
            "name": "Belajar Penerapan Data Science",
            "technology": "Data,Machine Learning",
            "hours_to_study": 40,
            "rating": "4.89",
            "level": "INTERMEDIATE",
            "learning_path": "Data Scientist",
            "total_modules": 72,
            "registered_students": 427
        },
        {
            "id": 600,
            "name": "Belajar Dasar Structured Query Language (SQL)",
            "technology": "Data",
            "hours_to_study": 11,
            "rating": "4.87",
            "level": "FUNDAMENTAL",
            "learning_path": "Data Scientist",
            "total_modules": 44,
            "registered_students": 42370
        },
        {
            "id": 610,
            "name": "Menjadi Node.js Application Developer",
            "technology": "Web",
            "hours_to_study": 57,
            "rating": "4.83",
            "level": "PROFESSIONAL",
            "learning_path": "Back-End Developer",
            "total_modules": 155,
            "registered_students": 576
        },
        {
            "id": 615,
            "name": "Belajar Dasar Data Science",
            "technology": "Data,Machine Learning",
            "hours_to_study": 11,
            "rating": "4.83",
            "level": "FUNDAMENTAL",
            "learning_path": "Data Scientist",
            "total_modules": 50,
            "registered_students": 26869
        }
    ]
  }
